version: '3.9'

services:

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www/laravel
    volumes:
      - './laravel:/var/www/laravel'
    networks:
      - lara-network
    environment:
      - DB_HOST=mysqldb #same name as service below
      - DB_PORT=3306

  #web (nginx)
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www/laravel
    volumes:
      - './laravel:/var/www/laravel'
    networks:
      - lara-network
    ports: 
      - "8080:80"
      - "3000:3000"
    depends_on:
      - app

  #MYSQL DB
  mysqldb:
    image: mysql:8.1.0
    volumes:
      - ladata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=app" #named whatever the project is
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=rootpassword"
    ports:
      - "33061:3306"
    networks:
      - lara-network

  npm:
    image: node:alpine
    container_name: npm
    volumes:
      - ./laravel:/var/www/laravel
    ports:
      - 3100:3100
      - 3001:3001
    working_dir: /var/www/laravel
    profiles: ["npm"]
    entrypoint: ['npm']
    networks:
      - lara-network

#select volumes to use
volumes:
  ladata:

networks:
  lara-network:
    driver: bridge